import { Activity, Cpu, ReceiptText } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../api";
import { dateTime, EmptyState, ErrorState, LoadingState, money, PageHeader, StatusBadge } from "../components/ui";
import { useAsync } from "../hooks/useAsync";

export function ActivityPage() {
  const { data: missions, error, loading, reload } = useAsync(api.missions, [], 5_000);
  if (loading && !missions) return <LoadingState label="Loading economic activity" />;
  if (error && !missions) return <ErrorState message={error} retry={reload} />;
  const inferenceEvents = (missions ?? []).flatMap((mission) => mission.events.map((event) => ({ event, mission }))).filter(({ event }) => event.type === "inference.completed").sort((a, b) => b.event.createdAt.localeCompare(a.event.createdAt));
  const totalActual = (missions ?? []).reduce((sum, mission) => sum + mission.actualCostUsd, 0);
  const totalEstimated = (missions ?? []).reduce((sum, mission) => sum + mission.estimatedCostUsd, 0);
  const tokens = (missions ?? []).reduce((sum, mission) => sum + mission.usage.total, 0);
  return <><PageHeader eyebrow="Economic ledger" title="Spending & activity" description="Provider-reported actuals stay separate from conservative preflight estimates." /><div className="mb-6 grid gap-4 sm:grid-cols-3"><Summary label="Recorded actual spend" value={money(totalActual)} icon={<ReceiptText />} /><Summary label="Preflight estimates" value={money(totalEstimated)} icon={<Activity />} /><Summary label="Tokens processed" value={tokens.toLocaleString()} icon={<Cpu />} /></div><section className="card overflow-hidden"><div className="border-b border-line px-5 py-4"><h2 className="font-semibold text-ink">Inference ledger</h2><p className="mt-0.5 text-xs text-muted">One row per completed provider response</p></div>{inferenceEvents.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-line bg-canvas/60 text-[10px] uppercase tracking-wider text-muted"><th className="px-5 py-3 font-semibold">Mission</th><th className="px-4 py-3 font-semibold">Model</th><th className="px-4 py-3 font-semibold">Tokens</th><th className="px-4 py-3 font-semibold">Cost status</th><th className="px-5 py-3 text-right font-semibold">Time</th></tr></thead><tbody className="divide-y divide-line">{inferenceEvents.map(({ event, mission }) => <tr key={event.id} className="text-xs"><td className="max-w-xs px-5 py-4"><Link className="block truncate font-semibold text-ink hover:text-violet" to={`/app/missions/${mission.id}`}>{mission.objective}</Link><span className="mt-1 block"><StatusBadge status={mission.status} /></span></td><td className="px-4 py-4 text-muted">{event.model ?? "—"}</td><td className="px-4 py-4 font-medium text-ink">{event.usage?.total.toLocaleString() ?? "—"}</td><td className="px-4 py-4">{event.cost ? <><span className="font-semibold text-emerald-700">{money(event.cost.amount)}</span><span className="ml-2 rounded bg-emerald-50 px-1.5 py-1 text-[9px] font-bold uppercase text-emerald-700">Actual</span></> : <span className="font-semibold text-red-600">Cost missing</span>}</td><td className="px-5 py-4 text-right text-muted">{dateTime(event.createdAt)}</td></tr>)}</tbody></table></div> : <EmptyState icon={<ReceiptText className="h-6 w-6" />} title="No inference spend recorded" description="Provider-reported costs and model usage appear here after a mission starts." />}</section></>;
}

function Summary({ label, value, icon }: { label: string; value: string; icon: React.ReactElement }) { return <div className="card flex items-center gap-4 p-5"><span className="rounded-xl bg-violet/[.07] p-2.5 text-violet [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><p className="text-xs text-muted">{label}</p><p className="mt-1 text-xl font-bold text-ink">{value}</p></div></div>; }
