import type { CreativePlan, CreativeProject, CreativeQuote, CreativeShot } from "@auvra/shared";
import { ArrowDown, ArrowRight, ArrowUp, Check, Clapperboard, Coins, ImagePlus, Loader2, LockKeyhole, Play, Sparkles, WandSparkles } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { ApiClientError, api } from "../api";

const steps = ["Brief", "Assets + brand", "Creative direction", "Shot plan", "Cost approval", "Generation", "Preview"];
const money = (value: number | undefined) => value === undefined ? "Unverified" : `$${value.toFixed(3)}`;

export function CreativeStudio() {
  const [projects, setProjects] = useState<CreativeProject[]>([]); const [project, setProject] = useState<CreativeProject>(); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [safeMessage, setSafeMessage] = useState("");
  const [form, setForm] = useState({ name: "", objective: "", audience: "", keyMessage: "", cta: "", durationSeconds: 15 as 15 | 30, aspectRatio: "16:9" as "16:9" | "9:16", toneNotes: "Premium, precise, confident", qualityTarget: "premium" as "standard" | "premium" });
  useEffect(() => { void api.creativeProjects().then((items) => { setProjects(items); setProject(items[0]); }).catch((cause: Error) => setError(cause.message)); }, []);
  const latestQuote = project?.quotes.at(-1); const approved = [...(project?.quotes ?? [])].reverse().find((quote) => quote.status === "approved");
  const currentStep = project?.generations.length ? 5 : approved ? 5 : latestQuote ? 4 : project?.plan ? 3 : project?.assets.length ? 1 : 0;
  const run = async (label: string, action: () => Promise<CreativeProject | CreativeQuote | unknown>) => { setBusy(label); setError(""); setSafeMessage(""); try { await action(); if (project) setProject(await api.creativeProject(project.id)); setProjects(await api.creativeProjects()); } catch (cause) { const apiError = cause as ApiClientError; if (apiError.code === "VIDEO_GENERATION_DISABLED") setSafeMessage(apiError.message); else setError(apiError.message); } finally { setBusy(""); } };
  const create = async (event: FormEvent) => { event.preventDefault(); await run("create", async () => { const created = await api.createCreativeProject({ name: form.name, brief: { objective: form.objective, audience: form.audience, keyMessage: form.keyMessage, ...(form.cta ? { cta: form.cta } : {}), durationSeconds: form.durationSeconds, aspectRatio: form.aspectRatio, toneNotes: form.toneNotes, qualityTarget: form.qualityTarget } }); setProject(created); return created; }); };
  const patchShot = (shotId: string, patch: Partial<CreativeShot>) => setProject((current) => current?.plan ? { ...current, plan: { ...current.plan, shots: current.plan.shots.map((shot) => shot.id === shotId ? { ...shot, ...patch } : shot) } } : current);
  const moveShot = (shotId: string, delta: number) => setProject((current) => { if (!current?.plan) return current; const ordered = [...current.plan.shots].sort((a, b) => a.order - b.order); const from = ordered.findIndex((shot) => shot.id === shotId); const to = from + delta; if (from < 0 || to < 0 || to >= ordered.length) return current; const [moved] = ordered.splice(from, 1); ordered.splice(to, 0, moved!); return { ...current, plan: { ...current.plan, shots: ordered.map((shot, index) => ({ ...shot, order: index + 1 })) } }; });
  const totalDuration = useMemo(() => project?.plan?.shots.reduce((sum, shot) => sum + shot.durationSeconds, 0) ?? 0, [project?.plan]);

  return <div className="space-y-8">
    <section className="overflow-hidden rounded-[32px] border border-[#2f2550] bg-[#110c21] px-6 py-8 text-white shadow-[0_30px_100px_rgba(55,31,120,.18)] sm:px-9 lg:px-12 lg:py-11">
      <div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-3 py-1.5 text-xs font-semibold text-violet-200"><WandSparkles className="h-3.5 w-3.5" /> Premium Video Engine · V1</div><h1 className="max-w-3xl text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl lg:text-6xl">Give Auvra the material.<br /><span className="text-[#a88cff]">It directs the video.</span></h1><p className="mt-5 max-w-2xl text-sm leading-6 text-white/60 sm:text-base">Screenshots become evidence. Auvra extracts the meaning, locks the brand, invents the motion language, and reserves generative video for the moments that earn their cost.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-white/40">Direction principle</p><div className="mt-4 space-y-3 text-sm font-semibold"><p>Understand the content</p><p className="text-white/30">↓</p><p>Reimagine the presentation</p><p className="text-white/30">↓</p><p className="text-violet-200">Preserve the brand</p></div></div></div>
    </section>

    <div className="grid gap-2 sm:grid-cols-4 lg:grid-cols-7">{steps.map((step, index) => <div key={step} className={`rounded-xl border px-3 py-3 text-xs font-semibold ${index <= currentStep ? "border-violet/20 bg-violet/[.06] text-violet" : "border-line bg-white text-muted"}`}><span className="mr-2 text-[10px] opacity-60">0{index + 1}</span>{step}</div>)}</div>
    {error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : null}
    {safeMessage ? <div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="font-semibold">Development-safe mode</p><p className="mt-1">{safeMessage}</p></div></div> : null}

    {!project ? <form onSubmit={create} className="panel grid gap-5 p-6 sm:grid-cols-2 lg:p-8"><div className="sm:col-span-2"><h2 className="text-2xl font-semibold tracking-tight text-ink">Start with intent</h2><p className="mt-1 text-sm text-muted">Auvra chooses the engine after it understands the job.</p></div><Field label="Project name"><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="October product film" className="input" /></Field><Field label="Audience"><input required value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value })} placeholder="Operations leaders" className="input" /></Field><Field label="Objective"><textarea required value={form.objective} onChange={(e) => setForm({ ...form, objective: e.target.value })} placeholder="What should this video accomplish?" className="input min-h-24" /></Field><Field label="Key message"><textarea required value={form.keyMessage} onChange={(e) => setForm({ ...form, keyMessage: e.target.value })} placeholder="The one idea viewers must retain" className="input min-h-24" /></Field><Field label="Call to action"><input value={form.cta} onChange={(e) => setForm({ ...form, cta: e.target.value })} placeholder="Optional" className="input" /></Field><Field label="Tone"><input required value={form.toneNotes} onChange={(e) => setForm({ ...form, toneNotes: e.target.value })} className="input" /></Field><Field label="Duration"><select value={form.durationSeconds} onChange={(e) => setForm({ ...form, durationSeconds: Number(e.target.value) as 15 | 30 })} className="input"><option value={15}>15 seconds</option><option value={30}>30 seconds</option></select></Field><Field label="Format"><select value={form.aspectRatio} onChange={(e) => setForm({ ...form, aspectRatio: e.target.value as "16:9" | "9:16" })} className="input"><option value="16:9">Landscape · 16:9</option><option value="9:16">Portrait · 9:16</option></select></Field><button disabled={Boolean(busy)} className="button-primary sm:col-span-2 sm:w-fit">Create creative workspace <ArrowRight className="h-4 w-4" /></button></form> : <>
      <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet">Active project</p><h2 className="mt-1 text-3xl font-semibold tracking-tight text-ink">{project.name}</h2></div>{projects.length > 1 ? <select value={project.id} onChange={(e) => setProject(projects.find((item) => item.id === e.target.value))} className="input max-w-xs">{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select> : null}</div>
      <section className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><AssetPanel project={project} busy={busy} run={run} /><div className="panel p-6 lg:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Creative direction</p><h3 className="mt-2 text-2xl font-semibold text-ink">{project.plan?.conceptTitle ?? "Ready to direct"}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">{project.plan?.conceptSummary ?? "Auvra will turn the brief, source evidence, and brand lock into a composable shot graph."}</p></div><Sparkles className="h-5 w-5 text-violet" /></div><div className="mt-6 flex flex-wrap gap-3"><button disabled={Boolean(busy)} onClick={() => void run("analyze", () => api.analyzeCreativeProject(project.id))} className="button-secondary">{busy === "analyze" ? <Loader2 className="h-4 w-4 animate-spin" /> : <ImagePlus className="h-4 w-4" />} Analyze assets</button><button disabled={Boolean(busy)} onClick={() => void run("direct", () => api.directCreativeProject(project.id))} className="button-primary">{busy === "direct" ? <Loader2 className="h-4 w-4 animate-spin" /> : <WandSparkles className="h-4 w-4" />} Direct the film</button></div></div></section>
      {project.plan ? <section className="panel p-6 lg:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Shot graph</p><h3 className="mt-2 text-2xl font-semibold text-ink">Review the treatment</h3><p className="mt-1 text-sm text-muted">Edit exact copy, timing, scene mode, order, CTA, and permission to spend on generated motion.</p></div><p className={`text-sm font-semibold ${totalDuration === project.plan.durationSeconds ? "text-emerald-600" : "text-red-600"}`}>{totalDuration}s / {project.plan.durationSeconds}s</p></div><label className="mt-5 block max-w-xl"><span className="mb-2 block text-xs font-semibold text-ink">Closing CTA</span><input className="input" value={project.plan.closingCTA ?? ""} onChange={(event) => setProject({ ...project, plan: { ...project.plan!, closingCTA: event.target.value } })} /></label><div className="mt-6 space-y-3">{[...project.plan.shots].sort((a, b) => a.order - b.order).map((shot) => <ShotEditor key={shot.id} shot={shot} patch={(values) => patchShot(shot.id, values)} move={moveShot} />)}</div><div className="mt-5 flex flex-wrap gap-3"><button disabled={Boolean(busy) || totalDuration !== project.plan.durationSeconds} onClick={() => void run("save-plan", () => api.directCreativeProject(project.id, project.plan as CreativePlan))} className="button-secondary"><Check className="h-4 w-4" /> Save shot graph</button><button disabled={Boolean(busy) || totalDuration !== project.plan.durationSeconds} onClick={() => void run("quote", () => api.quoteCreativeProject(project.id))} className="button-primary"><Coins className="h-4 w-4" /> Build cost approval</button></div></section> : null}
      {latestQuote ? <QuotePanel quote={latestQuote} approved={approved?.id === latestQuote.id} busy={busy} approve={() => run("approve", () => api.approveCreativeQuote(project.id, latestQuote.id))} generate={() => run("generate", () => api.generateCreativeProject(project.id, latestQuote.id))} /> : null}
      <section className="panel p-6 lg:p-8"><p className="eyebrow">Generation + preview</p><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="flex min-h-48 items-center justify-center rounded-2xl border border-dashed border-line bg-canvas text-center"><div><Clapperboard className="mx-auto h-7 w-7 text-muted/50" /><p className="mt-3 text-sm font-semibold text-ink">Final composition awaits approved media</p><p className="mt-1 text-xs text-muted">Exact typography, logo, metrics, diagrams, and CTA stay deterministic.</p></div></div><div className="space-y-3">{project.generations.length ? project.generations.map((generation) => <div key={generation.id} className="rounded-xl border border-line p-4"><div className="flex justify-between text-sm"><span className="font-semibold text-ink">Shot {project.plan?.shots.find((shot) => shot.id === generation.shotId)?.order}</span><span className="capitalize text-muted">{generation.status.replace("_", " ")}</span></div><div className="mt-2 flex justify-between text-xs text-muted"><span>Reserved {money(generation.reservedCostUsd)}</span><span>Actual {money(generation.actualProviderCostUsd)}</span></div></div>) : <p className="text-sm leading-6 text-muted">No paid jobs have been submitted. Development-safe mode never shows fake progress.</p>}</div></div></section>
    </>}
  </div>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-ink">{label}</span>{children}</label>; }

function AssetPanel({ project, busy, run }: { project: CreativeProject; busy: string; run: (label: string, action: () => Promise<unknown>) => Promise<void> }) { const [files, setFiles] = useState<File[]>([]); const [role, setRole] = useState("source"); return <div className="panel p-6 lg:p-8"><p className="eyebrow">Assets + brand lock</p><h3 className="mt-2 text-xl font-semibold text-ink">Source material, not a template</h3><p className="mt-2 text-sm leading-6 text-muted">PNG, JPEG, WEBP, MP4, WEBM, MP3, or WAV. Files stay protected with the workspace.</p><input className="mt-5 block w-full text-xs text-muted file:mr-3 file:rounded-lg file:border-0 file:bg-violet/[.08] file:px-3 file:py-2 file:font-semibold file:text-violet" type="file" multiple accept="image/png,image/jpeg,image/webp,video/mp4,video/webm,audio/mpeg,audio/wav" onChange={(e) => setFiles(Array.from(e.target.files ?? []))} /><div className="mt-3 flex gap-2"><select value={role} onChange={(e) => setRole(e.target.value)} className="input"><option value="source">Source material</option><option value="logo">Logo</option><option value="wordmark">Wordmark</option><option value="reference_video">Reference video</option><option value="audio">Audio</option></select><button disabled={!files.length || Boolean(busy)} onClick={() => void run("upload", () => api.uploadCreativeAssets(project.id, files, role))} className="button-secondary shrink-0">Upload</button></div><div className="mt-5 flex flex-wrap gap-2">{project.assets.map((asset) => <span key={asset.id} className="rounded-full border border-line bg-canvas px-3 py-1.5 text-xs text-muted">{asset.role.replace("_", " ")} · {asset.originalName}</span>)}</div></div>; }

function ShotEditor({ shot, patch, move }: { shot: CreativeShot; patch: (values: Partial<CreativeShot>) => void; move: (shotId: string, delta: number) => void }) { return <div className="grid gap-4 rounded-2xl border border-line bg-white p-4 md:grid-cols-[48px_1fr_150px_110px]"><div><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-night text-xs font-bold text-white">{String(shot.order).padStart(2, "0")}</div><div className="mt-1 flex"><button aria-label="Move shot up" onClick={() => move(shot.id, -1)} className="p-1 text-muted hover:text-violet"><ArrowUp className="h-3 w-3" /></button><button aria-label="Move shot down" onClick={() => move(shot.id, 1)} className="p-1 text-muted hover:text-violet"><ArrowDown className="h-3 w-3" /></button></div></div><div><input className="w-full border-0 bg-transparent p-0 text-base font-semibold text-ink outline-none" value={shot.exactCopy[0] ?? ""} onChange={(e) => patch({ exactCopy: [e.target.value, ...shot.exactCopy.slice(1)] })} /><p className="mt-1 text-xs text-muted">{shot.visualConcept}</p><label className="mt-3 flex items-center gap-2 text-xs font-medium text-muted"><input type="checkbox" checked={shot.allowGenerativeVideo} onChange={(e) => patch({ allowGenerativeVideo: e.target.checked })} /> May use generated video</label></div><select value={shot.visualMode} onChange={(e) => patch({ visualMode: e.target.value as CreativeShot["visualMode"] })} className="input text-xs"><option value="motion_graphic">Motion graphic</option><option value="product_proof">Product proof</option><option value="hybrid">Hybrid</option><option value="generative_video">Generated motion</option></select><label className="input flex items-center gap-2 text-xs"><input min={1} max={15} step={1} type="number" value={shot.durationSeconds} onChange={(e) => patch({ durationSeconds: Number(e.target.value) })} className="w-10 border-0 bg-transparent outline-none" /> sec</label></div>; }

function QuotePanel({ quote, approved, busy, approve, generate }: { quote: CreativeQuote; approved: boolean; busy: string; approve: () => Promise<unknown>; generate: () => Promise<unknown> }) { return <section className="overflow-hidden rounded-[28px] border border-[#ded7f6] bg-[#f9f7ff] p-6 lg:p-8"><div className="grid gap-6 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow">Exact cost approval</p><h3 className="mt-2 text-2xl font-semibold text-ink">{money(quote.estimatedProviderCostUsd)} estimated · {money(quote.reservedCostUsd)} maximum reserve</h3><p className="mt-2 text-sm text-muted">Deterministic composition provider cost: $0.000 · Pricing reviewed {quote.pricingAsOf} · {Math.round((quote.safetyMultiplier - 1) * 100)}% safety margin</p><div className="mt-5 space-y-2">{quote.items.map((item) => <div key={item.shotId} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-white px-4 py-3 text-xs"><span className="font-semibold text-ink">{item.model ? "Generated scene" : "Deterministic scene"}</span><span className="text-muted">{item.seconds}s · {item.quoteUnavailable ? item.reason : `${money(item.estimatedProviderCostUsd)} → reserve ${money(item.reservedCostUsd)}`}</span></div>)}</div></div><div className="flex min-w-48 flex-col justify-end gap-3">{!approved ? <button disabled={Boolean(busy) || quote.items.some((item) => item.quoteUnavailable)} onClick={() => void approve()} className="button-primary"><LockKeyhole className="h-4 w-4" /> Approve exact quote</button> : <button disabled={Boolean(busy)} onClick={() => void generate()} className="button-primary"><Play className="h-4 w-4" /> Generate approved plan</button>}<p className="text-center text-[11px] text-muted">Approval never bypasses the server safety flag.</p></div></div></section>; }
